name: Create Pull Request

on:
  push:
    branches-ignore:
      - 'main'

env:
  BASE_BRANCH: main
  ASSIGNEE: ${{ vars.ASSIGNEE }}
  REVIEWER: ${{ vars.REVIEWER }}

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Check
        id: check
        run: echo "count=$(gh pr list -B ${{ env.BASE_BRANCH }} -H ${{ github.ref_name }} | wc -l)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        if: ${{ steps.check.outputs.count == 0 }}
        run: gh pr create --fill -B ${{ env.BASE_BRANCH }} -t ${{ github.ref_name }} -a ${{ env.ASSIGNEE }} -r ${{ env.REVIEWER }}
