name: OpenTofu Docs

on:
  pull_request:
    branches:
      - main
    paths:
      - 'aws/*/*.tf'

jobs:
  tofu-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        # v4.1.1
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Generate module docs
        # v1.0.0
        uses: terraform-docs/gh-actions@f6d59f89a280fa0a3febf55ef68f146784b20ba0
        with:
          working-dir: aws/*/
          output-file: README.md
          output-method: inject
          git-push: "true"
